DROP TABLE IF EXISTS sim_responses;
DROP TABLE IF EXISTS pre_sim_responses;

CREATE TABLE sim_responses (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    q1 TEXT NOT NULL,
    q2 TEXT NOT NULL,
    q3 TEXT NOT NULL,
    q4 TEXT NOT NULL,
    q5 TEXT NOT NULL
);

CREATE TABLE pre_sim_responses (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pq1 TEXT NOT NULL,
    pq2 TEXT NOT NULL,
    pq3 TEXT NOT NULL,
    pq4 TEXT NOT NULL,
    pq5 TEXT NOT NULL
);